"""
Frontend PROJECT build service (agentic, container-sandboxed).

Unlike the removed single-file HTML flow (one text-model call returning a single
inline index.html), this drives an autonomous coding CLI (Claude Code, headless) inside
a throwaway Docker container to produce a COMPLETE multi-file React + Vite + TS
project that the agent itself builds and self-checks.

Sandbox properties (validated by PoC):
  * runs as the non-root ``node`` user (the CLI refuses bypassPermissions as root);
  * the only host-visible write is the mounted ``/out`` dir — node_modules and the
    npm cache live only in the container fs and die with ``--rm``;
  * the deliverable copied to /out is source + built ``dist`` ONLY.

This deliberately steps OUTSIDE the capability-routed AI provider abstraction:
the CLI owns its own Anthropic backend, so this is an agent-EXECUTION lane, not a
single ``generate_text`` call. Token usage is reported back via the CLI's terminal
``result`` event so the caller can meter it into the credit system.

TWO agents cooperate inside the one container (mirrors the slicer's Codex setup):
  * Claude Code is the PRIMARY engine — it writes the project and self-checks.
  * When the UI needs REAL raster imagery (instead of emoji / placeholders),
    Claude triggers the bundled ``image-assets`` skill, which shells out to the
    OpenAI Codex CLI; Codex generates each picture with the OpenAI image model
    (``genimage.mjs`` -> gpt-image-2) and writes it into ``src/assets/``. Both the
    skill and the helper are written into the container at startup, so no app
    code is baked into the image. The asset lane is FAIL-SOFT: a missing
    OPENAI_API_KEY or an image error never sinks the build (Claude then falls
    back to CSS/SVG — the prompt forbids emoji either way).
"""
import json
import logging
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable, Optional

from werkzeug.utils import secure_filename

from backend.services.code import asset_lane
from backend.services.code.docker_env import (
    ANTHROPIC_RETRY_PROXY_BOOTSTRAP,
    anthropic_agent_credentials,
    anthropic_configured,
    container_user,
    host_workdir,
    mount_failure_hint,
)
from backend.services.prompts import prompt_store

logger = logging.getLogger(__name__)

PROMPT_DIR = Path(__file__).parent.parent.parent / "prompts" / "code"

# Per-file ceilings when collecting the deliverable, so a runaway file can't blow
# up the DB / artifact storage. Raster assets (generated by the image-assets
# skill) get a larger cap than text/source, plus a total budget so a runaway
# image set can't bloat the zip / on-disk site / GitHub commit.
_MAX_TEXT_BYTES = 512_000
_MAX_ASSET_BYTES = 4_000_000
_MAX_TOTAL_ASSET_BYTES = 24_000_000
# Bundler OUTPUT (the built dist's entry chunk / styles / sourcemaps / wasm) is
# routinely larger than a hand-written source file — a single React+Three.js app
# easily emits a ~700KB index-*.js. These are NOT runaway source files: index.html
# references them by hash, so dropping one 404s the preview's own entry script and
# the page goes blank. Give them a generous per-file cap (well above the text cap)
# so a built bundle is never silently skipped. They don't count against the raster
# image budget (they aren't images).
_MAX_BUNDLE_BYTES = 16_000_000
_BINARY_EXTS = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".avif", ".ico", ".bmp"}
_BUNDLE_EXTS = {".js", ".mjs", ".cjs", ".css", ".map", ".wasm"}

# Runs INSIDE the container. The agent's stream-json goes to stdout (streamed live
# to the host); in-container ``timeout`` guards every phase against a hang. Only
# source + built/synthesized dist are copied to the mounted /out.
#
# A single claude pass routinely fails to produce a clean build (it times out
# mid-write leaving a dangling import, or emits a type/resolution error). To make
# a previewable deliverable GUARANTEED, the build is a self-healing ladder:
#   1. npm run build (as generated)
#   2. one AI repair round  -- claude -p fed the build log, told to only fix
#   3. deterministic stub    -- node script back-fills every unresolved relative
#                               import (the dominant failure: a referenced file the
#                               agent never wrote) so resolution can't sink the build
#   4. vite build (no tsc)   -- bypass type-only errors and let the bundler emit
#   5. synthesized dist       -- a minimal static page, so dist is NEVER empty
# The reached rung is written to /out/degraded for the host to report.
_CONTAINER_SCRIPT = r"""
export HOME="${HOME:-/home/node}"
WORK=/tmp/work
mkdir -p "$WORK" && cd "$WORK"
# Iteration (二次开发) seed: when an existing project source was provided at
# /out/_base, copy it into the workdir so the agent EDITS it in place (真实续改)
# instead of generating fresh. No-op when /out/_base is absent. Removed afterwards
# so it never gets tarred into the published source/dist.
if [ -d /out/_base ] && [ -n "$(ls -A /out/_base 2>/dev/null)" ]; then
  cp -a /out/_base/. "$WORK"/ 2>/dev/null || true
  rm -rf /out/_base
  echo seeded > /out/seeded
fi
# P2-F: git checkpoint baseline (fail-soft; no git in image -> skipped). Gives the
# coding agent + repair rungs a known-good state to revert to and makes progress
# legible. node_modules/dist are ignored so commits stay small.
if command -v git >/dev/null 2>&1; then
  printf 'node_modules/\ndist/\n.cache/\n.npm/\n*.log\n' > "$WORK/.gitignore"
  ( cd "$WORK" && git init -q && git config user.email agent@worksflow.local \
    && git config user.name worksflow-agent && git add -A \
    && git commit -q -m "baseline" --allow-empty ) >/dev/null 2>&1 || true
fi
# `Skill` is added so Claude can trigger the bundled image-assets skill; Bash lets
# that skill (and Claude itself) shell out to the Codex CLI for asset generation.
CLAUDE_FLAGS="--output-format stream-json --verbose --permission-mode bypassPermissions --allowedTools Read Write Edit Bash Skill"

# __ANTHROPIC_PROXY_BOOTSTRAP__

# __ASSET_LANE_BOOTSTRAP__

# Emit a phase sentinel onto the JSON stream so the host timeline can narrate
# the recovery ladder (build phases write their output to /out logs, not stdout).
emit() { printf '%s\n' "{\"type\":\"fe_phase\",\"phase\":\"$1\"}"; }

# Run a command under an OPTIONAL wall-clock cap. A cap of "0" / "" / non-numeric
# means NO limit — the coding agent runs to completion instead of being killed
# mid-generate (exit 124) and degraded to a fallback page. Operators who would
# rather wait for a real build than ship a degraded one set FE_AGENT_TIMEOUT=0
# (see docker-compose). A cooperative cancel from the UI still stops the run.
run_capped() {  # usage: run_capped <seconds> cmd [args...]
  local secs="${1:-0}"; shift
  case "$secs" in (''|*[!0-9]*) secs=0 ;; esac
  if [ "$secs" -eq 0 ]; then
    "$@"
  else
    timeout "$secs" "$@"
  fi
}

# --- 1. Generate ---------------------------------------------------------
# Feed the prompt over stdin, NOT as a positional arg: the assembled prompt
# (requirements + flow + documents + style + figma) routinely exceeds Linux
# MAX_ARG_STRLEN (128KB per single argv string), so `claude -p "$(cat ...)"`
# would die at exec with "/usr/bin/timeout: Argument list too long" (E2BIG,
# surfaced as exit 126). `claude -p` reads the whole stdin as the prompt.
run_capped "${FE_AGENT_TIMEOUT:-720}" claude -p $CLAUDE_FLAGS < /out/prompt.txt
echo "$?" > /out/claude_exit
mkdir -p /out/project

# The prompt asks the agent to initialize directly in $WORK, but autonomous
# coding agents sometimes create one extra project directory. Publish the first
# buildable-looking project root so a harmless nesting mistake is recoverable.
PROJECT_ROOT="$WORK"
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
  PACKAGE_JSON="$(find "$WORK" -maxdepth 3 -name package.json -not -path '*/node_modules/*' -print -quit 2>/dev/null)"
  if [ -n "$PACKAGE_JSON" ]; then
    PROJECT_ROOT="$(dirname "$PACKAGE_JSON")"
  fi
fi
echo "$PROJECT_ROOT" > /out/project_root

# Write the deterministic repair + fallback tools (run only on the failure path).
cat > /tmp/repair.mjs <<'REPAIR_EOF'
import fs from 'node:fs';
import path from 'node:path';

const projectRoot = process.argv[2];
const srcDir = path.join(projectRoot, 'src');
const CODE_EXTS = ['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'];
const RES_EXTS = [...CODE_EXTS, '.json', '.css', '.scss', '.sass', '.less'];
const STYLE_EXTS = ['.css', '.scss', '.sass', '.less'];

function walk(dir) {
  let out = [];
  let entries = [];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    if (e.name === 'node_modules' || e.name === '.git' || e.name === 'dist') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out = out.concat(walk(p));
    else out.push(p);
  }
  return out;
}

function resolveSpec(fromFile, spec) {
  const base = path.resolve(path.dirname(fromFile), spec);
  const ext = path.extname(base);
  if (ext && RES_EXTS.includes(ext)) return fs.existsSync(base) ? base : null;
  for (const e of RES_EXTS) if (fs.existsSync(base + e)) return base + e;
  for (const e of RES_EXTS) if (fs.existsSync(path.join(base, 'index' + e))) return path.join(base, 'index' + e);
  return null;
}

function targetPathFor(fromFile, spec) {
  const base = path.resolve(path.dirname(fromFile), spec);
  if (path.extname(base)) return base;
  const isComponent = /^[A-Z]/.test(path.basename(base));
  return base + (isComponent ? '.tsx' : '.ts');
}

function clauseInfo(clause) {
  const info = { hasDefault: false, named: new Set() };
  if (!clause) return info;
  clause = clause.trim();
  const brace = clause.match(/\{([\s\S]*)\}/);
  const before = clause.split('{')[0].replace(/\*\s+as\s+\w+/, '').replace(/,/g, ' ').trim();
  if (before) info.hasDefault = true;
  if (brace) {
    for (const part of brace[1].split(',')) {
      let name = part.trim().split(/\s+as\s+/)[0].trim().replace(/^type\s+/, '');
      if (name && name !== 'type') info.named.add(name);
    }
  }
  return info;
}

function ident(name) {
  const s = name.replace(/[^A-Za-z0-9_$]/g, '_');
  return /^[0-9]/.test(s) ? '_' + s : (s || 'Placeholder');
}

const stmtRe = /import\s+([\s\S]*?)\s+from\s+['"]([^'"]+)['"]|import\s+['"]([^'"]+)['"]|export\s+(?:\*|\{[\s\S]*?\})\s+from\s+['"]([^'"]+)['"]/g;
const sources = walk(srcDir).filter((p) => CODE_EXTS.includes(path.extname(p)));
const targets = new Map();

for (const file of sources) {
  let code;
  try { code = fs.readFileSync(file, 'utf8'); } catch { continue; }
  let m;
  while ((m = stmtRe.exec(code))) {
    const spec = m[2] || m[3] || m[4];
    if (!spec || !(spec.startsWith('./') || spec.startsWith('../'))) continue;
    if (resolveSpec(file, spec)) continue;
    const tp = targetPathFor(file, spec);
    let entry = targets.get(tp);
    if (!entry) { entry = { isStyle: STYLE_EXTS.includes(path.extname(tp)), named: new Set(), hasDefault: false }; targets.set(tp, entry); }
    const info = clauseInfo(m[1]);
    if (info.hasDefault) entry.hasDefault = true;
    for (const n of info.named) entry.named.add(n);
  }
}

let created = 0;
for (const [tp, entry] of targets) {
  if (fs.existsSync(tp)) continue;
  fs.mkdirSync(path.dirname(tp), { recursive: true });
  if (entry.isStyle) {
    fs.writeFileSync(tp, '/* auto-generated placeholder stylesheet */\n');
    created++;
    continue;
  }
  const ext = path.extname(tp);
  const isTsx = ext === '.tsx' || ext === '.jsx';
  const id = ident(path.basename(tp, ext));
  const lines = ['// Auto-generated placeholder: original module missing before build.'];
  if (isTsx) {
    lines.push("import { createElement } from 'react';");
    lines.push(`function ${id}(_props: any) {`);
    lines.push(`  return createElement('div', { 'data-placeholder': '${id}', style: { padding: 16, opacity: 0.6 } }, '${id} (placeholder)');`);
    lines.push('}');
    lines.push(`export default ${id};`);
    for (const n of entry.named) { if (ident(n) !== id) lines.push(`export const ${ident(n)}: any = ${id};`); }
  } else {
    lines.push('const placeholder: any = {};');
    if (entry.hasDefault) lines.push('export default placeholder;');
    for (const n of entry.named) lines.push(`export const ${ident(n)}: any = placeholder;`);
    if (!entry.hasDefault && entry.named.size === 0) lines.push('export {};');
  }
  fs.writeFileSync(tp, lines.join('\n') + '\n');
  created++;
}
console.log(`stub-repair: created ${created} placeholder file(s)`);
REPAIR_EOF

cat > /tmp/fallback.mjs <<'FALLBACK_EOF'
import fs from 'node:fs';
import path from 'node:path';

const projectRoot = process.argv[2];
const buildLogPath = process.argv[3];
const distDir = path.join(projectRoot, 'dist');
fs.mkdirSync(distDir, { recursive: true });

let log = '';
try { log = fs.readFileSync(buildLogPath, 'utf8').slice(-3000); } catch {}
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const html = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>前端工程预览(降级)</title>
<style>
  body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#0f172a;color:#e2e8f0;display:flex;min-height:100vh;align-items:center;justify-content:center;padding:24px}
  .card{max-width:760px;background:#1e293b;border:1px solid #334155;border-radius:16px;padding:32px}
  h1{margin:0 0 12px;font-size:20px}
  p{line-height:1.7;color:#cbd5e1}
  code{background:#0f172a;padding:2px 6px;border-radius:6px}
  pre{background:#0f172a;border:1px solid #334155;border-radius:10px;padding:16px;overflow:auto;max-height:280px;font-size:12px;color:#fca5a5}
</style></head>
<body><div class="card">
  <h1>项目已生成,但自动构建未通过</h1>
  <p>已为你保留完整源码(可在右侧下载源码 zip)。自动构建在多轮修复(AI 修复 + 确定性补桩 + Vite 兜底)后仍未通过,故合成此降级预览页,以保证始终有可预览产物。</p>
  <p>请下载源码后本地运行 <code>npm install &amp;&amp; npm run build</code> 查看完整报错。下面是构建日志节选:</p>
  <pre>${esc(log) || '(无构建日志)'}</pre>
</div></body></html>`;

fs.writeFileSync(path.join(distDir, 'index.html'), html);
console.log('fallback dist written');
FALLBACK_EOF

# runtimecheck.mjs (P1-C) — serve the built dist and load it in a headless browser,
# capturing console/page errors + a screenshot. The browser is OPTIONAL: when the
# image hasn't baked Playwright/Puppeteer the smoke is skipped (ran:false), so it
# never sinks the build (same fail-soft contract as the Codex asset lane).
cat > /tmp/runtimecheck.mjs <<'RUNTIMECHK_EOF'
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const distDir = process.argv[2];
const outPath = process.argv[3];
const shotPath = process.argv[4];

function writeResult(obj) {
  try { fs.mkdirSync(path.dirname(outPath), { recursive: true }); } catch {}
  try { fs.writeFileSync(outPath, JSON.stringify(obj)); } catch {}
}

if (!distDir || !fs.existsSync(path.join(distDir, 'index.html'))) {
  writeResult({ ran: false, reason: 'no dist/index.html' });
  process.exit(0);
}

// Resolve a headless browser from the dedicated /opt/runtime-smoke install
// (a bare ESM import won't find it from the project cwd) with graceful fallbacks.
const requireSmoke = createRequire('/opt/runtime-smoke/');
let launcher = null;
try { launcher = (await import('playwright')).chromium; } catch {}
if (!launcher) { try { launcher = requireSmoke('playwright').chromium; } catch {} }
if (!launcher) { try { launcher = requireSmoke('playwright-core').chromium; } catch {} }
if (!launcher) { try { const pp = await import('puppeteer'); launcher = pp.default || pp; } catch {} }
if (!launcher) { writeResult({ ran: false, reason: 'no headless browser module' }); process.exit(0); }

const MIME = {
  '.html': 'text/html', '.js': 'text/javascript', '.mjs': 'text/javascript',
  '.css': 'text/css', '.json': 'application/json', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.webp': 'image/webp', '.gif': 'image/gif', '.ico': 'image/x-icon',
  '.wasm': 'application/wasm', '.map': 'application/json',
  '.woff': 'font/woff', '.woff2': 'font/woff2', '.ttf': 'font/ttf',
};
const distAbs = path.resolve(distDir);
const server = http.createServer((req, res) => {
  try {
    let p = decodeURIComponent((req.url || '/').split('?')[0]);
    if (p === '/' || p === '') p = '/index.html';
    let fp = path.join(distAbs, p);
    if (!fp.startsWith(distAbs)) { res.writeHead(403); res.end(); return; }
    if (!fs.existsSync(fp) || fs.statSync(fp).isDirectory()) fp = path.join(distAbs, 'index.html');
    const buf = fs.readFileSync(fp);
    res.writeHead(200, { 'Content-Type': MIME[path.extname(fp).toLowerCase()] || 'application/octet-stream' });
    res.end(buf);
  } catch { res.writeHead(500); res.end(); }
});
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const port = server.address().port;

const consoleErrors = [];
const pageErrors = [];
const timeoutMs = Number(process.env.FE_RUNTIME_TIMEOUT || 60) * 1000;
const uniq = (a) => [...new Set(a)].slice(0, 30);
let browser = null;
try {
  browser = await launcher.launch({ args: ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu'] });
  const page = await browser.newPage();
  page.on('console', (m) => { try { if (m.type() === 'error') consoleErrors.push(String(m.text()).slice(0, 300)); } catch {} });
  page.on('pageerror', (e) => { try { pageErrors.push(String((e && e.message) || e).slice(0, 300)); } catch {} });
  page.on('dialog', (d) => { try { d.dismiss().catch(() => {}); } catch {} });
  page.on('popup', (p) => { try { p.close().catch(() => {}); } catch {} });
  await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'load', timeout: timeoutMs });
  await new Promise((r) => setTimeout(r, 1500));

  // --- Interactive crawl: drive the app like a user (fill inputs, click every
  // control) and capture interaction-triggered console/page errors + dead controls
  // (a click that changes nothing: no DOM mutation, no nav, no network, no error).
  // This is the "test by driving the app, not reading code" gate. Bounded + fail-soft.
  const interactions = { total: 0, clicked: 0, filled: 0, dead_controls: [] };
  const MAXI = Number(process.env.FE_RUNTIME_MAX_INTERACTIONS || 25);
  const deadline = Date.now() + Math.min(timeoutMs, 75000);
  const HOME = `http://127.0.0.1:${port}`;
  try {
    const fields = await page.$$('input:not([type=hidden]):not([type=submit]):not([type=button]):not([type=checkbox]):not([type=radio]):not([type=file]), textarea');
    for (const el of fields.slice(0, 15)) {
      try {
        const t = (await el.getAttribute('type')) || 'text';
        const v = t === 'email' ? 'demo@example.com' : t === 'password' ? 'Demo1234!' : t === 'number' ? '1' : t === 'tel' ? '13800000000' : 'test';
        await el.fill(v, { timeout: 1500 });
        interactions.filled++;
      } catch {}
    }
    const controls = await page.$$('button:not([disabled]), [role="button"], a[href]:not([href=""]):not([href="#"]), input[type="submit"], [onclick]');
    interactions.total = controls.length;
    for (let i = 0; i < Math.min(controls.length, MAXI); i++) {
      if (Date.now() > deadline) break;
      const el = controls[i];
      let label = '';
      try { label = ((await el.innerText().catch(() => '')) || (await el.getAttribute('aria-label').catch(() => '')) || (await el.getAttribute('title').catch(() => '')) || '').replace(/\s+/g, ' ').trim().slice(0, 40); } catch {}
      let beforeLen = 0; try { beforeLen = await page.evaluate(() => (document.body ? document.body.innerHTML.length : 0)); } catch {}
      const beforeUrl = page.url();
      const errBefore = consoleErrors.length + pageErrors.length;
      let net = false; const onReq = () => { net = true; };
      try { page.on('request', onReq); } catch {}
      try { await el.click({ timeout: 2000 }); interactions.clicked++; await new Promise((r) => setTimeout(r, 300)); } catch {}
      try { page.off('request', onReq); } catch {}
      try { if (!page.url().startsWith(HOME)) { await page.goto(HOME, { waitUntil: 'load', timeout: timeoutMs }); await new Promise((r) => setTimeout(r, 250)); continue; } } catch {}
      let afterLen = beforeLen; try { afterLen = await page.evaluate(() => (document.body ? document.body.innerHTML.length : 0)); } catch {}
      const errAfter = consoleErrors.length + pageErrors.length;
      const changed = afterLen !== beforeLen || page.url() !== beforeUrl || net || errAfter !== errBefore;
      if (!changed && label) interactions.dead_controls.push(label);
    }
    // Keyboard surfaces (P-C): games / canvas apps respond to keys, not clicks —
    // drive a few common controls so INPUT-triggered runtime errors surface via the
    // page listeners. A key that does nothing is NOT flagged (apps legitimately
    // ignore most keys); only thrown errors count. Inside the inner try so a harness
    // hiccup stays a soft interactions.error, never a hard page_error. Bounded.
    try {
      for (const k of ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Space', 'Enter']) {
        if (Date.now() > deadline) break;
        try { await page.keyboard.press(k); await new Promise((r) => setTimeout(r, 120)); interactions.keys = (interactions.keys || 0) + 1; } catch {}
      }
    } catch {}
  } catch (e) { interactions.error = String((e && e.message) || e).slice(0, 200); }
  interactions.dead_controls = [...new Set(interactions.dead_controls)].slice(0, 20);

  try { fs.mkdirSync(path.dirname(shotPath), { recursive: true }); await page.screenshot({ path: shotPath }); } catch {}
  const ce = uniq(consoleErrors), pe = uniq(pageErrors);
  writeResult({ ran: true, ok: ce.length === 0 && pe.length === 0, console_errors: ce, page_errors: pe, interactions, screenshot: fs.existsSync(shotPath) ? path.basename(shotPath) : null });
} catch (e) {
  writeResult({ ran: true, ok: false, console_errors: uniq(consoleErrors), page_errors: uniq([...pageErrors, 'smoke harness: ' + ((e && e.message) || e)]) });
} finally {
  try { if (browser) await browser.close(); } catch {}
  try { server.close(); } catch {}
}
process.exit(0);
RUNTIMECHK_EOF

# progress.mjs (P2-F) — write a deterministic progress.json (build + runtime
# status) into the project, preserving any agent-maintained progress under merge.
cat > /tmp/progress.mjs <<'PROGRESS_EOF'
import fs from 'node:fs';
import path from 'node:path';
const root = process.argv[2];
const read = (f) => { try { return fs.readFileSync(f, 'utf8').trim(); } catch { return ''; } };
let rc = null;
try { rc = JSON.parse(read('/out/runtime_check.json')); } catch {}
const status = {
  build_exit: read('/out/npm_build_exit') || null,
  degraded: read('/out/degraded') || null,
  runtime: rc ? { ran: !!rc.ran, ok: !!rc.ok, console_errors: (rc.console_errors || []).length, page_errors: (rc.page_errors || []).length } : null,
  by: 'fe-agent',
};
const p = path.join(root, 'progress.json');
let existing = null;
try { existing = JSON.parse(fs.readFileSync(p, 'utf8')); } catch {}
let out;
if (existing && typeof existing === 'object' && !Array.isArray(existing)) out = existing;
else if (existing != null) out = { agent_notes: existing };
else out = {};
out.build = status;
try { fs.writeFileSync(p, JSON.stringify(out, null, 2)); } catch {}
PROGRESS_EOF

DEGRADED=""
run_build() {
  ( cd "$PROJECT_ROOT" && timeout "${FE_AGENT_BUILD_TIMEOUT:-180}" npm run build ) > /out/npm_build.log 2>&1
  echo "$?" > /out/npm_build_exit
}
build_ok() { [ "$(cat /out/npm_build_exit 2>/dev/null)" = "0" ]; }

if [ -f "$PROJECT_ROOT/package.json" ]; then
  emit install
  ( cd "$PROJECT_ROOT" && timeout "${FE_AGENT_NPM_TIMEOUT:-240}" npm install --no-audit --no-fund --prefer-offline ) > /out/npm_install.log 2>&1
  echo "$?" > /out/npm_install_exit

  # rung 1: build as generated
  emit build
  run_build

  # rung 2: one AI repair round, fed the build log
  if ! build_ok; then
    emit ai-repair
    # Same MAX_ARG_STRLEN guard as the generate step: build the repair prompt
    # (base prompt + tail of the build log) into a file and pipe it over stdin
    # instead of passing it as a positional arg, so a large prompt/log can never
    # blow exec with "Argument list too long".
    {
      cat /out/repair_prompt.txt
      printf '\n\n# 构建报错(节选)\n'
      tail -c 6000 /out/npm_build.log 2>/dev/null
    } > /out/repair_full_prompt.txt
    ( cd "$PROJECT_ROOT" && run_capped "${FE_AGENT_REPAIR_TIMEOUT:-300}" claude -p $CLAUDE_FLAGS < /out/repair_full_prompt.txt )
    echo "$?" > /out/claude_repair_exit
    run_build
    build_ok && DEGRADED="ai-repair"
  fi

  # rung 3: deterministic stub of every unresolved relative import
  if ! build_ok; then
    emit stub
    node /tmp/repair.mjs "$PROJECT_ROOT" > /out/stub_repair.log 2>&1
    echo "$?" > /out/stub_repair_exit
    run_build
    build_ok && DEGRADED="stub"
  fi

  # rung 4: skip tsc, let Vite bundle whatever resolves
  if ! build_ok; then
    emit vite-only
    ( cd "$PROJECT_ROOT" && timeout "${FE_AGENT_BUILD_TIMEOUT:-180}" npx --no-install vite build ) > /out/npm_build.log 2>&1
    echo "$?" > /out/npm_build_exit
    build_ok && DEGRADED="vite-only"
  fi
fi

# rung 5 / final guarantee: never ship an empty dist.
if [ ! -f "$PROJECT_ROOT/dist/index.html" ]; then
  emit fallback
  node /tmp/fallback.mjs "$PROJECT_ROOT" /out/npm_build.log > /out/fallback.log 2>&1
  DEGRADED="fallback"
fi
echo "$DEGRADED" > /out/degraded

# --- Runtime smoke (P1-C): load the built dist in a headless browser and capture
# console/page errors + a screenshot. Fail-soft: no browser module in the image
# -> ran:false (skipped), never sinks the build. Activated once the fe-agent image
# bakes Playwright/Chromium (see backend/docker/fe-agent/Dockerfile).
emit runtime-check
run_capped "${FE_RUNTIME_TIMEOUT:-90}" node /tmp/runtimecheck.mjs "$PROJECT_ROOT/dist" /out/runtime_check.json /out/runtime/screenshot.png > /out/runtime_check.log 2>&1 || true

# --- Progress checkpoint (P2-F): record build + runtime status, then commit. ---
node /tmp/progress.mjs "$PROJECT_ROOT" > /dev/null 2>&1 || true
if command -v git >/dev/null 2>&1; then
  ( cd "$PROJECT_ROOT" && git add -A && git commit -q -m "build + verify checkpoint" --allow-empty ) >/dev/null 2>&1 || true
fi

# --- Collect deliverable (source + built/synthesized dist) ---------------
if [ -d "$PROJECT_ROOT" ]; then
  (
    cd "$PROJECT_ROOT" && \
    tar \
      --exclude='./node_modules' \
      --exclude='./.git' \
      --exclude='./.cache' \
      --exclude='./.npm' \
      --exclude='./*.log' \
      -cf - .
  ) | (cd /out/project && tar -xf -)
fi
"""

# Splice the gateway retry-proxy bootstrap in BEFORE the first claude call so every
# claude pass (generate + repair) routes through the localhost retry shim when a
# flaky gateway is configured. No-op for the official API. See docker_env.py.
_CONTAINER_SCRIPT = _CONTAINER_SCRIPT.replace(
    "# __ANTHROPIC_PROXY_BOOTSTRAP__", ANTHROPIC_RETRY_PROXY_BOOTSTRAP
)

# Splice the SHARED asset lane (backend/services/code/asset_lane.py — same module
# Dev Mode injects) with the one-shot parameters: diagnostics under /out and the
# style context sliced out of the assembled prompt (/out/prompt.txt), preserving
# the pre-extraction behaviour/diagnostics contract exactly.
_CONTAINER_SCRIPT = _CONTAINER_SCRIPT.replace(
    "# __ASSET_LANE_BOOTSTRAP__",
    asset_lane.render_bootstrap(
        style_context_path="/out/prompt.txt",
        diagnostics_dir="/out",
        style_extract="prompt_sections",
    ),
)


class FrontendProjectService:
    """Generate a runnable multi-file frontend project via a sandboxed agent."""

    def __init__(self):
        self.image = os.getenv("FE_AGENT_IMAGE", "fe-agent:latest")
        self.docker = os.getenv("DOCKER_BIN", "docker")
        # Per-phase budgets handed to the in-container `timeout` guards. The
        # self-healing ladder (generate + repair + several builds) can run long,
        # so the host's hard ceiling is the SUM of phases plus margin, NOT a single
        # claude budget. The in-container timeouts are the real per-phase guard;
        # total_timeout only backstops a container that never exits.
        # Set FE_AGENT_TIMEOUT / FE_AGENT_REPAIR_TIMEOUT / FE_AGENT_TOTAL_TIMEOUT to
        # 0 to DISABLE the cap for that phase — the agent then runs to completion
        # instead of being killed (124) and degraded. Only a cooperative cancel or
        # the agent finishing stops the run.
        self.gen_timeout = int(os.getenv("FE_AGENT_TIMEOUT", "720"))
        self.repair_timeout = int(os.getenv("FE_AGENT_REPAIR_TIMEOUT", "300"))
        self.npm_timeout = int(os.getenv("FE_AGENT_NPM_TIMEOUT", "240"))
        self.build_timeout = int(os.getenv("FE_AGENT_BUILD_TIMEOUT", "180"))
        self.total_timeout = int(os.getenv("FE_AGENT_TOTAL_TIMEOUT", "2400"))
        # Asset-generation lane (image-assets skill -> Codex -> image model):
        # per-`gen-assets`-call budget and per-image API budget, both in-container.
        self.codex_timeout = int(os.getenv("FE_CODEX_TIMEOUT", "420"))
        self.genimage_timeout = int(os.getenv("FE_GENIMAGE_TIMEOUT", "180"))
        # Runtime browser-smoke (P1-C): headless load of the built dist to capture
        # console/page errors. Optional — skipped fail-soft when the image has no
        # browser baked in (see backend/docker/fe-agent/Dockerfile).
        self.runtime_timeout = int(os.getenv("FE_RUNTIME_TIMEOUT", "90"))

    # --- prompt assembly -----------------------------------------------------
    def _load_prompt(self, name: str) -> str:
        # Mongo-backed (admin-editable); falls back to the bundled default under
        # PROMPT_DIR when Mongo is unavailable.
        return prompt_store.get(f"code/{name}")

    @staticmethod
    def _fill(template: str, **values: str) -> str:
        out = template
        for key, value in values.items():
            out = out.replace(f"[[{key}]]", value if value is not None else "")
        return out

    def _build_prompt(
        self, fill_vals: dict, edit_mode: bool, base_files: dict,
        change_instruction: str, change_plan: str,
    ) -> str:
        """Pick + fill the generation prompt (edit-mode variant for 二次开发续改)."""
        if not edit_mode:
            return self._fill(self._load_prompt("frontend_project_prompt.txt"), **fill_vals)
        base_list = "\n".join(f"- {p}" for p in sorted(base_files)[:300])
        edit_vals = dict(
            fill_vals,
            CHANGE_INSTRUCTION=(change_instruction or "")[:4_000],
            CHANGE_PLAN=(change_plan or "")[:4_000],
            BASE_FILES=base_list,
        )
        try:
            return self._fill(self._load_prompt("frontend_project_edit_prompt.txt"), **edit_vals)
        except Exception:  # noqa: BLE001 — edit template missing: prepend a续改 preamble
            base = self._fill(self._load_prompt("frontend_project_prompt.txt"), **fill_vals)
            return (
                "【二次开发·基于现有项目续改】当前目录已是现有前端工程,请只针对下述变更"
                "修改/新增相关页面、组件、路由与 API 调用,保持其余文件不变,不要整体重写。\n"
                f"变更要求:{(change_instruction or '')[:4000]}\n执行计划:\n{(change_plan or '')[:4000]}\n\n"
                + base
            )

    @staticmethod
    def _seed_base(base_dir: "Path", files: dict) -> None:
        """Write the existing project source under workdir/_base (binary-safe).

        Hardened against path traversal: a crafted zip member name like ``../../x``
        must not escape ``base_dir`` and write onto the host. Absolute paths, ``..``
        segments, and anything that resolves outside base_dir are skipped.
        """
        base_resolved = base_dir.resolve()
        written = 0
        for rel, content in files.items():
            if written > 4000:
                break
            norm = str(rel).replace("\\", "/")
            if not norm or norm.startswith("/") or ".." in norm.split("/"):
                continue
            try:
                dest = base_dir / norm
                resolved = dest.resolve()
                if base_resolved != resolved and base_resolved not in resolved.parents:
                    continue  # escaped base_dir → skip
                dest.parent.mkdir(parents=True, exist_ok=True)
                data = content if isinstance(content, (bytes, bytearray)) else str(content).encode("utf-8")
                dest.write_bytes(bytes(data))
                written += 1
            except Exception:  # noqa: BLE001
                continue

    @staticmethod
    def _extract_json(text: str) -> Optional[dict]:
        """Tolerant single-object JSON parse (code-fence / prefix tolerant)."""
        if not text:
            return None
        cleaned = text.strip()
        fenced = re.search(r"```(?:json)?\s*(.*?)```", cleaned, re.DOTALL | re.IGNORECASE)
        if fenced:
            cleaned = fenced.group(1).strip()
        if not cleaned.startswith("{"):
            match = re.search(r"(\{.*\})", cleaned, re.DOTALL)
            if match:
                cleaned = match.group(1)
        try:
            value = json.loads(cleaned)
            return value if isinstance(value, dict) else None
        except json.JSONDecodeError:
            logger.warning("project review: failed to parse model JSON output")
            return None

    def review_project(
        self,
        *,
        source_digest: str,
        requirements_registry: str,
        style_prompt: str = "",
        features_block: str = "",
        house_rules_report: str = "",
        runtime_report: str = "",
        extra_directive: str = "",
        on_model_call=None,
    ) -> Optional[dict]:
        """Skeptical, rubric-graded acceptance review of the generated project.

        One text-model call (on the reliable text lane) returns a structured
        verdict ``{verdict, scores, fr_coverage, feature_results, blocking_issues,
        advisory_issues, issues, summary}``. The evaluator is fed the deterministic
        signals (``house_rules_report`` / ``runtime_report``) + the acceptance
        ``features_block`` so its judgment is grounded, and its ``blocking_issues``
        drive the verify->repair loop. Returns ``None`` when no text provider is
        configured or on any failure (never raises).
        """
        from backend.services.ai import get_text_provider

        provider = get_text_provider()
        if not provider or not provider.is_configured():
            return None
        prompt = self._fill(
            self._load_prompt("frontend_project_critic_prompt.txt"),
            REQUIREMENTS=requirements_registry or "",
            STYLE_PROMPT=style_prompt or "",
            SOURCE=source_digest or "",
            FEATURES=features_block or "(本次未提供功能清单)",
            HOUSE_RULES=house_rules_report or "(确定性房规检查未发现问题)",
            RUNTIME=runtime_report or "(本次未运行运行时冒烟)",
        )
        if extra_directive:
            prompt += (
                "\n\n# 本次审查侧重(在完成完整 rubric 的同时,尤其严格审查以下方面)\n"
                + extra_directive
            )
        provider_name = getattr(provider, "provider_name", None)
        model_name = getattr(provider, "model", None)
        try:
            result = provider.generate_text(prompt)
        except Exception as error:  # noqa: BLE001 — advisory, never fatal
            logger.warning("project review model call raised: %s", error)
            if on_model_call:
                on_model_call(prompt=prompt, text=None, success=False, error=str(error),
                              provider=provider_name, model=model_name)
            return None
        if on_model_call:
            on_model_call(
                prompt=prompt, text=result.text if result.success else None,
                success=result.success, error=result.error,
                provider=provider_name, model=model_name,
            )
        if not result.success:
            return None
        return self._extract_json(result.text)

    def is_configured(self) -> bool:
        return anthropic_configured()

    def assets_enabled(self) -> bool:
        """Whether the image-assets skill (Codex -> OpenAI image model) can run.

        Independent of ``is_configured`` (which gates the primary Claude engine):
        with no OPENAI_API_KEY the build still succeeds, it just produces no
        generated raster assets (the agent falls back to CSS/SVG)."""
        return bool(os.getenv("OPENAI_API_KEY"))

    # --- public API ----------------------------------------------------------
    # Total budget for the Figma design block injected into the prompt. Visual
    # detail comes from the rendered images (the agent Reads them on demand), so
    # the prompt only carries a compact per-frame IR summary — keeping it bounded
    # even when a whole file has many frames.
    _FIGMA_BLOCK_BUDGET = 18_000

    def _figma_design_block(
        self, frames: Optional[list]
    ) -> tuple[str, list[tuple[str, str]]]:
        """Build the [[FIGMA_DESIGN]] prompt text + the (dest, src) render copies.

        ``frames`` items: ``{name, ir_text, render_path}``. Each frame becomes one
        page/route; its render is referenced as ``design/<dest>.png`` (mounted at
        ``/out/design/<dest>.png`` in the container) for the agent to ``Read``.
        """
        if not frames:
            return "", []
        head = [
            "# Figma 设计稿(视觉真值 — 优先级高于上面的文字风格 / UI 基调)",
            f"本产品有 {len(frames)} 个画板,每个画板对应一个页面/路由。",
            "实现每个页面前,先用 Read 工具读取它的设计图(在 design/ 目录下)作为视觉真值,"
            "精确还原布局、配色、字号、间距与层级;下方 IR 给出精确数值(hex/字号/间距)。",
            "设计稿与文字风格/UI 基调冲突时,以设计稿为准。",
        ]
        sections: list[str] = []
        copies: list[tuple[str, str]] = []
        used = 0
        for index, frame in enumerate(frames):
            name = frame.get("name") or f"frame{index + 1}"
            safe = secure_filename(name) or f"frame{index + 1}"
            dest = f"{index + 1:02d}-{safe}.png"
            src = frame.get("render_path")
            has_img = bool(src and Path(src).exists())
            if has_img:
                copies.append((dest, str(src)))
            ir = (frame.get("ir_text") or "").strip()
            ir = ir[: max(0, self._FIGMA_BLOCK_BUDGET - used)]
            used += len(ir)
            part = [f"\n## 画板 {index + 1}:{name}"]
            part.append(
                f"设计图: design/{dest}(用 Read 工具查看)" if has_img else "(无渲染图,仅依据下方 IR)"
            )
            if ir:
                part.append(f"设计 IR:\n{ir}")
            sections.append("\n".join(part))
        return "\n".join(head) + "\n" + "\n".join(sections), copies

    def build_project(
        self,
        *,
        requirement: str,
        requirements_doc: str = "",
        development_flow: str = "",
        documents_digest: str = "",
        style_prompt: str = "",
        ui_baseline_prompt: str = "",
        context_ledger: str = "",
        contract_block: str = "",
        figma_frames: Optional[list] = None,
        base_files: Optional[dict] = None,
        change_instruction: str = "",
        change_plan: str = "",
        on_event: Optional[Callable[[dict], None]] = None,
        is_cancelled: Optional[Callable[[], bool]] = None,
    ) -> dict:
        """Run the containerized agent through its self-healing build ladder.

        ``base_files`` (二次开发 iteration): when provided, the existing project
        source is seeded so the agent EDITS it per ``change_instruction`` /
        ``change_plan`` instead of regenerating (真实续改); the build ladder + dist
        collection are unchanged so deploy/preview consume the output as before.

        Returns ``{success, degraded, degraded_reason, error, files, dist_files,
        summary, usage, cost_usd, workdir}``. The container always produces a
        previewable ``dist`` (a synthesized notice page in the worst case), so
        ``success`` is True whenever the agent wrote any source; ``degraded`` /
        ``degraded_reason`` report which recovery rung produced the dist. Never
        raises on agent/model failure; raises only on infrastructure errors
        (docker missing, container never exits).
        """
        if not self.is_configured():
            return self._empty("ANTHROPIC_API_KEY not configured")

        figma_block, figma_copies = self._figma_design_block(figma_frames)
        # Keep each upstream doc bounded so the filled prompt stays small enough
        # for the container agent to finish within FE_AGENT_TIMEOUT. The BMAD
        # stage docs are detailed (long); an oversized prompt makes Claude Code
        # time out and fall back to a degraded build. ``documents_digest`` is
        # already capped upstream (``_MAX_DIGEST_CHARS``).
        _cap = 16_000
        edit_mode = bool(base_files)
        fill_vals = dict(
            CONTEXT_LEDGER=context_ledger or "",
            REQUIREMENT=(requirement or "")[:4_000],
            REQUIREMENTS_DOC=(requirements_doc or "")[:_cap],
            DEVELOPMENT_FLOW=(development_flow or "")[:_cap],
            DOCUMENTS=documents_digest or "",
            STYLE_PROMPT=(style_prompt or "")[:_cap],
            UI_BASELINE=(ui_baseline_prompt or "")[:6_000],
            FIGMA_DESIGN=figma_block,
            # Full-stack mode: when a shared API contract is injected the frontend
            # calls the REAL backend (via window.__API_BASE__) instead of using
            # localStorage; empty in standalone mode (backward compatible).
            CONTRACT=(contract_block or "")[:9_000],
        )
        prompt = self._build_prompt(
            fill_vals, edit_mode, base_files or {}, change_instruction, change_plan
        )

        workdir = Path(tempfile.mkdtemp(prefix="fe-agent-"))
        # The container runs as the non-root `node` user (uid 1000) and writes
        # the deliverable to this mounted dir. mkdtemp is 0700 (host user only);
        # on real Linux the container uid couldn't write it (Docker Desktop for
        # Mac is permissive and hides this), so open it up explicitly.
        os.chmod(workdir, 0o777)
        (workdir / "prompt.txt").write_text(prompt, encoding="utf-8")
        # Edit mode: seed the existing project source so the container copies it
        # into the agent workdir (真实续改). Binary-safe; skips pathological files.
        if base_files:
            self._seed_base(workdir / "_base", base_files)
        # The AI repair rung reuses this prompt; the container appends the live
        # build log before invoking claude a second time.
        (workdir / "repair_prompt.txt").write_text(
            self._load_prompt("frontend_project_repair_prompt.txt"), encoding="utf-8"
        )
        # Drop the Figma render images where the container agent can Read them
        # (/out/design/*.png). World-readable so the non-root `node` uid can open
        # them on real Linux (Docker Desktop for Mac is permissive).
        if figma_copies:
            design_dir = workdir / "design"
            design_dir.mkdir(parents=True, exist_ok=True)
            os.chmod(design_dir, 0o777)
            for dest, src in figma_copies:
                try:
                    shutil.copyfile(src, design_dir / dest)
                    os.chmod(design_dir / dest, 0o644)
                except OSError:
                    logger.warning("failed to stage figma render %s", src)
        # Anthropic credential injection: ANTHROPIC_AUTH_TOKEN (+ ANTHROPIC_BASE_URL)
        # for a gateway like zentao.panlaxy.io, else ANTHROPIC_API_KEY. Secrets are
        # passed by NAME (value pulled from `env` below) so they never land in argv.
        cred_flags, cred_env = anthropic_agent_credentials()

        user = container_user()
        cmd = [
            self.docker, "run", "--rm",
            "--user", user,
            *cred_flags,
            # OPENAI_API_KEY passed by NAME (value pulled from `env` below) so it
            # doesn't show up in the `docker run` argv / process list.
            "-e", "OPENAI_API_KEY",
            "-e", f"FE_AGENT_TIMEOUT={self.gen_timeout}",
            "-e", f"FE_AGENT_REPAIR_TIMEOUT={self.repair_timeout}",
            "-e", f"FE_AGENT_NPM_TIMEOUT={self.npm_timeout}",
            "-e", f"FE_AGENT_BUILD_TIMEOUT={self.build_timeout}",
            "-e", f"FE_CODEX_TIMEOUT={self.codex_timeout}",
            "-e", f"FE_GENIMAGE_TIMEOUT={self.genimage_timeout}",
            "-e", f"FE_RUNTIME_TIMEOUT={self.runtime_timeout}",
        ]
        if user != "node":
            # When matching the host UID the image's /home/node is owned by uid
            # 1000 and is not writable. Use /tmp as HOME instead (always 1777).
            cmd += ["-e", "HOME=/tmp"]
        # Non-secret OpenAI image config passthrough, so the in-container genimage
        # call stays aligned with the platform's image provider settings.
        for key in ("OPENAI_BASE_URL", "OPENAI_IMAGE_MODEL", "OPENAI_IMAGE_QUALITY", "OPENAI_IMAGE_SIZE"):
            value = os.getenv(key)
            if value:
                cmd += ["-e", f"{key}={value}"]
        # Optional persistent npm cache across runs (default OFF). Set FE_AGENT_NPM_CACHE
        # to a Docker volume name (or host path) to speed up repeat installs / survive a
        # flaky registry. Empty = unchanged behaviour (fresh per-run cache). Validate with
        # one real generation before relying on it (container user must be able to write
        # the mount). ``--prefer-offline`` (above) makes the warm cache actually used.
        _npm_cache = os.getenv("FE_AGENT_NPM_CACHE", "").strip()
        if _npm_cache:
            cmd += ["-v", f"{_npm_cache}:/npm-cache", "-e", "NPM_CONFIG_CACHE=/npm-cache"]
        cmd += ["-v", f"{host_workdir(workdir)}:/out", self.image, "bash", "-c", _CONTAINER_SCRIPT]

        env = dict(os.environ, **cred_env)
        # OPENAI_API_KEY drives the image-assets skill (Codex). Optional: when
        # unset the build still runs, just with no generated raster assets.
        openai_key = os.getenv("OPENAI_API_KEY")
        if openai_key:
            env["OPENAI_API_KEY"] = openai_key

        # The ladder runs claude up to twice (generate + repair); accumulate the
        # terminal `result` events so cost/usage metering reflects BOTH passes.
        result_events: list[dict] = []
        non_json_stdout: list[str] = []
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True, bufsize=1, env=env,
        )
        try:
            for line in proc.stdout:
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    non_json_stdout.append(line[:500])
                    non_json_stdout = non_json_stdout[-20:]
                    continue  # non-JSON noise on stdout — ignore
                if event.get("type") == "result":
                    result_events.append(event)
                if on_event:
                    try:
                        on_event(event)
                    except Exception:  # noqa: BLE001 - a bad callback must not kill the run
                        logger.exception("on_event callback raised")
                if is_cancelled and is_cancelled():
                    proc.kill()
                    return self._empty("cancelled")
            # total_timeout <= 0 means "wait forever" — pairs with the in-container
            # FE_AGENT_TIMEOUT=0 (uncapped agent). A run is then bounded only by the
            # agent finishing or a cooperative cancel, never by a wall-clock kill.
            proc.wait(timeout=self.total_timeout if self.total_timeout > 0 else None)
        except subprocess.TimeoutExpired:
            proc.kill()
            raise RuntimeError("frontend project agent timed out")
        finally:
            stderr = proc.stderr.read() if proc.stderr else ""
            if stderr:
                logger.info("fe-agent stderr: %s", stderr[:2000])

        docker_exit = proc.returncode
        claude_exit = self._read_exit_code(workdir / "claude_exit")
        npm_install_exit = self._read_exit_code(workdir / "npm_install_exit")
        npm_build_exit = self._read_exit_code(workdir / "npm_build_exit")
        npm_install_log = self._read_text(workdir / "npm_install.log")
        npm_build_log = self._read_text(workdir / "npm_build.log")
        # Which recovery rung produced the dist: "" (clean first build), or one of
        # ai-repair / stub / vite-only / fallback. Anything non-empty is degraded;
        # "fallback" means the dist is a synthesized notice page, not a real build.
        degraded_reason = self._read_text(workdir / "degraded").strip() or None
        files = self._collect(workdir / "project", exclude_top="dist")
        dist_files = self._collect(workdir / "project" / "dist")

        # Runtime smoke (P1-C): parse the headless-browser findings + screenshot
        # (both absent fail-soft when the image bakes no browser → ran:false).
        runtime_check = None
        _rc_raw = self._read_text(workdir / "runtime_check.json")
        if _rc_raw:
            try:
                runtime_check = json.loads(_rc_raw)
            except json.JSONDecodeError:
                runtime_check = None
        runtime_screenshot = None
        _shot = workdir / "runtime" / "screenshot.png"
        if _shot.exists():
            try:
                runtime_screenshot = _shot.read_bytes()
            except OSError:
                runtime_screenshot = None

        # Asset-lane diagnostics: was Codex even present (i.e. was fe-agent
        # rebuilt?), did Claude actually invoke gen-assets, and how many raster
        # assets landed in the source? Lets the host explain a "no assets" run.
        asset_log = self._read_text(workdir / "asset_gen.log")
        asset_lane = {
            "codex_available": bool(self._read_text(workdir / "codex_path").strip()),
            "gen_assets_available": bool(self._read_text(workdir / "gen_assets_path").strip()),
            "openai_key": bool(os.getenv("OPENAI_API_KEY")),
            "calls": sum(1 for ln in asset_log.splitlines() if ln.startswith("invoked:")),
            "assets": sum(1 for key in files if Path(key).suffix.lower() in _BINARY_EXTS),
            "log": asset_log.strip()[:1000],
        }

        # Sum cost/usage across every claude pass (generate + optional repair).
        summary, usage, cost, is_error = "", {}, 0.0, True
        if result_events:
            summary = next(
                (r.get("result") for r in result_events if isinstance(r.get("result"), str)),
                "",
            )
            cost = sum(float(r.get("total_cost_usd") or 0.0) for r in result_events)
            usage = self._merge_usage(result_events)
            is_error = bool(result_events[-1].get("is_error"))

        # The container always synthesizes a previewable dist, so a run is
        # publishable whenever the agent produced source. Hard-fail only when the
        # agent produced nothing at all (config/auth error) -> runtime refunds it.
        success = (docker_exit == 0) and bool(files) and bool(dist_files)
        degraded = success and bool(degraded_reason)
        return {
            "success": success,
            "degraded": degraded,
            "degraded_reason": degraded_reason if degraded else None,
            "error": None if success else self._format_failure(
                docker_exit=docker_exit,
                claude_exit=claude_exit,
                npm_install_exit=npm_install_exit,
                npm_build_exit=npm_build_exit,
                is_error=is_error,
                files=files,
                dist_files=dist_files,
                summary=summary,
                stderr=stderr,
                non_json_stdout=non_json_stdout,
                npm_install_log=npm_install_log,
                npm_build_log=npm_build_log,
            ),
            "files": files,
            "dist_files": dist_files,
            "summary": summary,
            "usage": usage,
            "cost_usd": cost,
            "asset_lane": asset_lane,
            "runtime_check": runtime_check,
            "runtime_screenshot": runtime_screenshot,
            "workdir": str(workdir),
        }

    # --- helpers -------------------------------------------------------------
    @staticmethod
    def _empty(error: str) -> dict:
        return {
            "success": False, "degraded": False, "degraded_reason": None,
            "error": error, "files": {}, "dist_files": {},
            "summary": "", "usage": {}, "cost_usd": 0.0, "asset_lane": {},
            "runtime_check": None, "runtime_screenshot": None, "workdir": None,
        }

    @staticmethod
    def _merge_usage(events: list[dict]) -> dict:
        """Sum integer token counters across every claude `result` event."""
        merged: dict = {}
        for event in events:
            usage = event.get("usage") or {}
            for key, value in usage.items():
                if isinstance(value, (int, float)) and not isinstance(value, bool):
                    merged[key] = merged.get(key, 0) + value
                elif key not in merged:
                    merged[key] = value
        return merged

    @staticmethod
    def _read_exit_code(path: Path) -> int | None:
        try:
            raw = path.read_text(encoding="utf-8").strip()
            return int(raw) if raw else None
        except (OSError, ValueError):
            return None

    @staticmethod
    def _read_text(path: Path) -> str:
        try:
            return path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return ""

    @staticmethod
    def _clip(text: str, limit: int = 1200) -> str:
        text = (text or "").strip()
        return text if len(text) <= limit else f"{text[:limit]}..."

    def _format_failure(
        self,
        *,
        docker_exit: int | None,
        claude_exit: int | None,
        npm_install_exit: int | None,
        npm_build_exit: int | None,
        is_error: bool,
        files: dict,
        dist_files: dict,
        summary: str,
        stderr: str,
        non_json_stdout: list[str],
        npm_install_log: str,
        npm_build_log: str,
    ) -> str:
        reasons: list[str] = []
        # A bind-mount / OCI create failure (DooD) means the agent container never
        # started — surface an actionable hint instead of a cryptic OCI error.
        mount_hint = mount_failure_hint(stderr)
        if mount_hint:
            reasons.append(mount_hint)
        if docker_exit not in (0, None):
            reasons.append(f"container exited with code {docker_exit}")
        if claude_exit not in (0, None):
            reasons.append(f"claude exited with code {claude_exit}")
        if npm_install_exit not in (0, None):
            reasons.append(f"npm install exited with code {npm_install_exit}")
        if npm_build_exit not in (0, None):
            reasons.append(f"npm run build exited with code {npm_build_exit}")
        if npm_build_exit is None:
            reasons.append("npm run build did not run")
        if is_error:
            reasons.append("claude reported an error")
        if not files:
            reasons.append("no source files were published")
        if not dist_files:
            reasons.append("no built dist files were published")

        details: list[str] = []
        if summary:
            details.append(f"summary: {self._clip(summary)}")
        if stderr:
            details.append(f"stderr: {self._clip(stderr)}")
        if non_json_stdout:
            details.append(f"stdout: {self._clip(chr(10).join(non_json_stdout))}")
        if npm_build_log:
            details.append(f"build log: {self._clip(npm_build_log)}")
        elif npm_install_log:
            details.append(f"install log: {self._clip(npm_install_log)}")

        headline = "; ".join(reasons) or "agent did not produce a buildable project"
        return " | ".join([headline, *details])

    def _collect(self, root: Path, exclude_top: Optional[str] = None) -> dict:
        """Return ``{relative_path: bytes}`` for files under ``root``.

        Binary-aware: source/text and generated raster assets are both read as
        raw bytes, so the zip / on-disk dist / GitHub commit keep real image data
        intact (a text-only collector would have corrupted PNGs into empty
        strings). Source text files keep a tight per-file cap; raster assets get a
        larger per-file cap plus a total budget so a runaway image set can't bloat
        the artifact; built bundles (.js/.css/.map/.wasm) get a generous cap so the
        bundler's own large entry chunk is never dropped (which would 404 the
        served preview's entry script and blank the page)."""
        out: dict[str, bytes] = {}
        if not root.exists():
            return out
        asset_budget = _MAX_TOTAL_ASSET_BYTES
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(root)
            if exclude_top and rel.parts and rel.parts[0] == exclude_top:
                continue
            suffix = path.suffix.lower()
            is_asset = suffix in _BINARY_EXTS
            if is_asset:
                cap = _MAX_ASSET_BYTES
            elif suffix in _BUNDLE_EXTS:
                cap = _MAX_BUNDLE_BYTES
            else:
                cap = _MAX_TEXT_BYTES
            try:
                size = path.stat().st_size
                if size > cap:
                    logger.warning("skip %s: %d bytes exceeds cap", rel, size)
                    continue
                if is_asset:
                    if size > asset_budget:
                        logger.warning("skip asset %s: total asset budget exhausted", rel)
                        continue
                    asset_budget -= size
                out[str(rel)] = path.read_bytes()
            except OSError:
                continue
        return out


_service_instance: Optional[FrontendProjectService] = None


def get_frontend_project_service() -> FrontendProjectService:
    global _service_instance
    if _service_instance is None:
        _service_instance = FrontendProjectService()
    return _service_instance
